# Generated by Django 5.0.6 on 2024-06-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mexmonxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yulduzlar_soni', models.IntegerField()),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('haqida', models.TextField()),
                ('muddati', models.IntegerField()),
                ('narxi', models.IntegerField()),
                ('mexmonxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mexmonxona', to='config_app.mexmonxona')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='config_app.transport')),
            ],
        ),
    ]
